### ISSUE TITLE
impl Display and Debug on cxx-qt-lib types

### ISSUE THREAD

**Issue by Be-ing** [KDAB/cxx-qt#369] opened 2022-12-03 16:49 UTC
Implementing [std::format::Display](https://doc.rust-lang.org/std/fmt/trait.Display.html) and [std::format::Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html) on cxx-qt-lib's types would be nice.

**Comment by ahayzen-kdab** [comment] 2022-12-05 10:12
This is a duplicate of #53 ?

**Closed** 2022-12-05 15:18 UTC
Labels: good first issue
