### ISSUE TITLE
Examples with QtWidgets

### ISSUE THREAD

**Issue by hanusek** [KDAB/cxx-qt#610] opened 2023-07-15 20:39 UTC
Hello!
I am looking for examples of QtWidget (not QML/QtQuick). Where can I find it?

**Comment by Be-ing** [comment] 2023-07-16 07:59
We haven't made those yet. Hopefully I'll get around to it in the next couple weeks.

Closing as a duplicate of #143.

**Closed by Be-ing** 2023-07-16 07:59 UTC

**Comment by ahayzen-kdab** [comment] 2023-07-17 08:41
Note that exposing QObjects / list models from Rust -> a C++ widgets app is no different to using QML.

Driving widgets from Rust only should be simpler now we support normal CXX extern blocks. Just that a lot of the widgets API is pointer driven, so you either need to pass around raw pointers in Rust (which uses unsafe blocks) or have wrapper methods that convert these to/from UniquePtr/SharedPtr. Some of this could likely be templated though.

And I also am unsure about trying to add widgets API into cxx-qt-lib as that is a huge surface of API to support. I think instead having enough templated C++ methods that can be used or documented how to do it would be more useful.

**Comment by hanusek** [comment] 2023-07-17 18:32
@ahayzen-kdab 
I expected CXX-Qt to be like PySide6 for Rust. Thanks for your reply.
https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/index.html

**Comment by ahayzen-kdab** [comment] 2023-07-17 19:06
Note that it is very easy to expose C++ types through to Rust via CXX opaque type, eg if one wanted to use `QPainter` as a type in an invokable, and then wanted to use `fillRect` in the method it would just require the following CXX block.

```rust
    unsafe extern "C++" {
        type QPainter;
        include!(<QtGui/QPainter>);

        #[rust_name = "fill_rect"]
        fn fillRect(self: Pin<&mut QPainter>, rectangle: &QRectF, color: &QColor);
    }
```

However we are also evaluating which common types make sense for us to maintain in cxx-qt-lib to avoid boilerplate for the developer etc. Also note that other types have more things to gain from us providing types, as for types such as QString we are able to mark it as trivial for CXX rather than it being an opaque type (as QPainter is here below), whereas types like QPainter are likely not possible to be made trivial so there is a cost to benefit battle here.

I do think it's likely that we'll be adding more types and/or helpers for you to reach the types over time though, but we are also still evolving the main API.
