### ISSUE TITLE
Can't compile begin_move_rows() function in an inherited QAbstractListModel.

### ISSUE THREAD

**Issue by ChrisCochrun** [KDAB/cxx-qt#697] opened 2023-10-11 15:31 UTC
I'm not sure if this is normal or not, but I can't get my Rust Model to inherit and compile when using begin_move_rows from the QAbstractListModel.

Version: 0.5.3

Here is my code for an example. Notice how I can compile end_move_rows...just not begin...
```
#[cxx_qt::inherit]
    extern "C++" {
        unsafe fn begin_insert_rows(
            self: Pin<&mut qobject::ServiceItemMod>,
            parent: &QModelIndex,
            first: i32,
            last: i32,
        );
        unsafe fn end_insert_rows(
            self: Pin<&mut qobject::ServiceItemMod>,
        );

        // cxx-qt can't build this function for some reason
        // unsafe fn begin_move_rows(
        //     self: Pin<&mut qobject::ServiceItemMod>,
        //     source_parent: &QModelIndex,
        //     source_first: i32,
        //     source_last: i32,
        //     destination_parent: &QModelIndex,
        //     destination_child: i32,
        // );

        unsafe fn end_move_rows(
            self: Pin<&mut qobject::ServiceItemMod>,
        );

        unsafe fn begin_remove_rows(
            self: Pin<&mut qobject::ServiceItemMod>,
            parent: &QModelIndex,
            first: i32,
            last: i32,
        );
        unsafe fn end_remove_rows(
            self: Pin<&mut qobject::ServiceItemMod>,
        );

        unsafe fn begin_reset_model(
            self: Pin<&mut qobject::ServiceItemMod>,
        );
        unsafe fn end_reset_model(
            self: Pin<&mut qobject::ServiceItemMod>,
        );
 }
```

**Comment by ahayzen-kdab** [comment] 2023-10-11 16:25
Thanks for taking the time to report this issue.

Looking at https://doc.qt.io/qt-6/qabstractitemmodel.html#beginMoveRows the signature in C++ is

```cpp
bool QAbstractItemModel::beginMoveRows(const [QModelIndex](https://doc.qt.io/qt-6/qmodelindex.html) &sourceParent, int sourceFirst, int sourceLast, const [QModelIndex](https://doc.qt.io/qt-6/qmodelindex.html) &destinationParent, int destinationChild)
```

I suspect that the issue is that it returns a `bool`, so you likely need to use the following (note the `-> bool`) as CXX is probably trying to match the whole signature.

```rust
        unsafe fn begin_move_rows(
            self: Pin<&mut qobject::ServiceItemMod>,
            source_parent: &QModelIndex,
            source_first: i32,
            source_last: i32,
            destination_parent: &QModelIndex,
            destination_child: i32,
        ) -> bool;
```

If this doesn't work, could you paste the full output you get when it goes wrong?

**Comment by ChrisCochrun** [comment] 2023-10-11 16:45
Ahhhh. Yes, that seems to have been my issue. Sorry if that seems like a silly question, I have been fighting it for a week now. I see some of the examples have that as well now. So the entire signature, including return type is needed.

**Comment by ahayzen-kdab** [comment] 2023-10-11 21:24
No problem, I initially didn't spot the return type either :-) ... I'll close the issue

**Closed by ahayzen-kdab** 2023-10-11 21:24 UTC
Labels: 🪲 bug, ❌ invalid
